server:
  port: 9002

spring:
  application:
    name: cloud-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.107:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'