server:
  port: 8803

spring:
  application:
    name: cloud-stream-rabbit-provider
  cloud:
    stream:
      binders:  # 在此处配置要绑定的rabbit的信息
        defaultRabbit:  # 表示定义的名称，用于和rabbitmq整合
          type: rabbit  # 消息组件类型
          environment:  # 设置rabbitmq的环境配置信息
            spring:
              rabbitmq:
                host: 192.168.0.107
                port: 5672
                username: guest
                password: guest
      bindings:   # 服务的整合治理
        input:    # 这个名字是一个通道的名称
          destinationn: studyExchange # 表示要定义的Exchange的名称
          content-type: application/json # 设置消息类型，本次为json
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置。
          group: atguiguA

eureka:
  client: # 客户端进行eureka的注册配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: receive-8802.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址